name: demo_v1

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - httpx=0.17.1
  - jinja2
  - numpy
  - openpyxl
  - pandas
  - pickleshare
  - osqp
  - joblib
  - pip
  - pip:
    - fastapi-plugins==0.6.0
    - python-multipart
    - imutils
    - scikit-learn
    - lightgbm
