name: env_ascore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas==1.4.4  
  - joblib==1.1.0
  - statsmodels==0.13.2
  - ipykernel
  - zipp  
  - pip
  - pip: 
    - optbinning==0.17.3
    - ortools==9.4.1874
