name: Create Conda Environment on Multiple OS

on:
  push:
    branches:
      - master  # Replace with your desired branch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, redhat-latest]  # Add other OS options if needed

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create Conda Environment
      run: conda env create -f environment.yml
      working-directory: ${{ github.workspace }}

    - name: Generate environment_spec.txt
      run: |
        conda list --explicit > environment_spec.txt
      working-directory: ${{ github.workspace }}

    - name: Push environment_spec.txt to Branch
      uses: ad-m/github-push-action@v1
      with:
        repo: https://github.com/nguyenngocbinh/Conda-Environment-on-Linux.git  # Replace with your repository URL
        branch: ${{ matrix.os }}-branch
        directory: ./  # The directory where environment_spec.txt is located
        github_token: ${{ secrets.GITHUB_TOKEN }}
