name: Create Conda Environment on Multiple OS

on:
  push:
    branches:
      - master  # Replace with your desired source branch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # , centos-latest, debian-latest, fedora-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Configure Git
      run: |
         git config --global user.email "nguyenngocbinhneu@gmail.com"
         git config --global user.name "Ngoc Binh"

    - name: Delete Existing Branch
      run: |
         git branch -D ${{ matrix.os }}-branch
      continue-on-error: true  # Ignore error if the branch doesn't exist
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create Conda Environment
      run: conda env create -f environment.yml
      working-directory: ${{ github.workspace }}

    - name: Generate Conda Environment Specification
      run: conda list --explicit > environment_spec.txt
      working-directory: ${{ github.workspace }}

    - name: Copy Conda Environments
      run: |
        # Create a temporary directory to store the environments
        mkdir -p temp_envs
        cp -r ~/miniconda3/envs/demo_v1/* temp_envs/
      working-directory: ${{ github.workspace }}
      
    - name: Save Environment Specification to Another Branch
      run: |
        git checkout -b ${{ matrix.os }}-branch        
        # git add environment_spec.txt
        git add *.*
        git commit -m "Add environment specification"
        git push origin ${{ matrix.os }}-branch --force
      working-directory: ${{ github.workspace }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Activate Conda Environment
    #   run: conda activate myenv
    #   working-directory: ${{ github.workspace }}

    # - name: Install Additional Dependencies (if needed)
    #   run: |
    #     conda install -c conda-forge some_package
    #   working-directory: ${{ github.workspace }}

    - name: Run Your Python Script
      run: python your_script.py
      working-directory: ${{ github.workspace }}
