name: Create Conda Environment and Download Specification

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create Conda Environment
      run: conda env create -f environment.yml
      working-directory: ${{ github.workspace }}

    - name: Generate Conda Environment Specification
      run: conda list --explicit > environment_spec.txt
      working-directory: ${{ github.workspace }}

    - name: Upload Specification as Workflow Artifact
      uses: actions/upload-artifact@v2
      with:
        name: environment-spec
        path: environment_spec.txt

    - name: Activate Conda Environment
      run: conda activate myenv
      working-directory: ${{ github.workspace }}

    # - name: Install Additional Dependencies (if needed)
    #   run: |
    #     conda install -c conda-forge some_package
    #   working-directory: ${{ github.workspace }}
      
    - name: Run Your Python Script
      run: python your_script.py
      working-directory: ${{ github.workspace }}
