name: Create Conda Environment and Save to Another Branch

on: [push]
# on:
#   push:
#     branches:
#       - feature-branch  # Replace with the name of your source branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure Git
      run: |
        git config --global user.email "nguyenngocbinhneu@gmail.com"
        git config --global user.name "Ngoc Binh"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create Red Hat 8.6 Docker Container
      run: |
        docker run --name redhat-container -d --privileged --cap-add SYS_ADMIN registry.fedoraproject.org/fedora:34 /sbin/init
        docker exec -it redhat-container bash
      shell: bash

    - name: Install Red Hat Subscription Manager
      run: |
        dnf install -y subscription-manager
        subscription-manager register --username=${{ secrets.REDHAT_USER }} --password=${{ secrets.REDHAT_PWD }} --auto-attach
      shell: bash

    - name: Install Conda in the Red Hat Container
      run: |
        dnf install -y wget
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda
        /opt/miniconda/bin/conda init
        source ~/.bashrc
      shell: bash

    - name: Create Conda Environment
      run: conda env create -f environment.yml
      working-directory: ${{ github.workspace }}

    - name: Generate Conda Environment Specification
      run: conda list --explicit > environment_spec.txt
      working-directory: ${{ github.workspace }}

    - name: Save Environment Specification to Another Branch
      run: |
        git checkout -b environment-branch
        git add environment_spec.txt
        git commit -m "Add environment specification"
        git push origin environment-branch
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Activate Conda Environment
    #   run: conda activate env_ascore
    #   working-directory: ${{ github.workspace }}

    # - name: Install Additional Dependencies (if needed)
    #   run: |
    #     conda install -c conda-forge some_package
    #   working-directory: ${{ github.workspace }}
      
    # - name: Run Your Python Script
    #   run: python your_script.py
    #   working-directory: ${{ github.workspace }}

    - name: Cleanup Red Hat Container
      run: docker stop redhat-container && docker rm redhat-container
