name: Create Conda Environment on Multiple OS

on:
  push:
    branches:
      - master

env:
  GIT_EMAIL: nguyenngocbinhneu@gmail.com
  GIT_NAME: Ngoc Binh
  CONDA_ENV_FILE: environment.yml
  PYTHON_SCRIPT: your_script.py
  ENV_NAME: "demo_v1"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure Git
        run: git config --global user.email "${{ env.GIT_EMAIL }}" && git config --global user.name "${{ env.GIT_NAME }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Switch to Branch
        run: git switch -C ${{ matrix.os }}-branch

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Create Conda Environment
        run: conda env create --name ${{ env.ENV_NAME }} --file ${{ env.CONDA_ENV_FILE }}
        working-directory: ${{ github.workspace }}

      - name: Generate Conda Environment Specification
        run: conda env export --name ${{ env.ENV_NAME }} > environment_spec.txt
        working-directory: ${{ github.workspace }}

      - name: Activate Conda Environment
        run: conda activate ${{ env.ENV_NAME }}
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Create Temporary Directory
        run: mkdir -p temp_env
        working-directory: ${{ github.workspace }}
        
      - name: Display $CONDA_PREFIX
        run: echo $CONDA_PREFIX
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Copy Conda Environments
        run: cp -r $CONDA_PREFIX/* temp_env/
        working-directory: ${{ github.workspace }}

      - name: Save Environment Specification to Another Branch
        run: |
          git add environment_spec.txt temp_env
          git commit -m "Add environment specification"
          git push origin ${{ matrix.os }}-branch --force
        working-directory: ${{ github.workspace }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Install Additional Dependencies (if needed)
      #   run: |
      #     conda install -c conda-forge some_package
      #   working-directory: ${{ github.workspace }}

      - name: Run Your Python Script
        run: python your_script.py
        working-directory: ${{ github.workspace }}
